### PR TITLE
Support service tags on creation.

### PR DESCRIPTION
**Pull request by multani**
The API doesn't expose updating tags yet: https://docs.opsgenie.com/docs/service-api#update-service

This is needed for https://github.com/opsgenie/terraform-provider-opsgenie/issues/144 and https://github.com/opsgenie/terraform-provider-opsgenie/pull/149

I'm looking for suggestions for the tests!

### CODE REVIEW

**Comment by ffahri** [comment]
@multani  is there anything left to add this pr ? if not you can set as a ready for review

**Comment by multani** [comment]
> @multani is there anything left to add this pr ? if not you can set as a ready for review

I think that's it!
If you have any suggestions for better tests, I can add them!

I think the fail build is unrelated though.

**Comment by multani** [comment]
(as a side note, it would be great to expose updating tags on the API as well!)

**Comment by multani** [comment]
Closing + reopening for triggering the CI build

**Pull request merged**
